package de.devin.monity.util

enum class Error {

    NONE,
    EMAIL_ALREADY_IN_USE,
    USERNAME_TAKEN,
    INVALID_ID_UUID_COMBINATION,
    INVALID_CONFIRMATION,
    EMAIL_NOT_FOUND,
    USER_NOT_FOUND,
    INVALID_PASSWORD,
    INVALID_RESET_REQUEST,
    INVALID_LOGIN_REQUEST

}