#HTTP Server configuration
host: "127.0.0.1"
port: 8808

#Deploy Settings
domain: "localhost:3000"
domainAPI: "localhost:8808"

#SQL Server configuration
sql_user: "root"
sql_password: ""
sql_port: 3306
sql_host: "localhost"
sql_db: "monity"

#email config
email_password: ""
email_user: ""
email_smtp_port: 456
email_hostname: "mail.gmx.net"