# This is a basic workflow to help you get started with Actions

name: detekt

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  detekt:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
       - name: "detekt"
         uses: natiginfo/action-detekt-all@1.21.0-RC2


